# Generated by Django 2.2.5 on 2019-09-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdtask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='contact',
        ),
        migrations.DeleteModel(
            name='ActivityStatus',
        ),
        migrations.DeleteModel(
            name='ContactSource',
        ),
        migrations.DeleteModel(
            name='ContactStatus',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='account',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='createdBy',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
